/**
 * @fileoverview gRPC-Web generated client stub for calculator
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.34.1
// source: calculator.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as calculator_pb from './calculator_pb'; // proto import: "calculator.proto"


export class CalculatorClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAdd = new grpcWeb.MethodDescriptor(
    '/calculator.Calculator/Add',
    grpcWeb.MethodType.UNARY,
    calculator_pb.CalcRequest,
    calculator_pb.CalcResponse,
    (request: calculator_pb.CalcRequest) => {
      return request.serializeBinary();
    },
    calculator_pb.CalcResponse.deserializeBinary
  );

  add(
    request: calculator_pb.CalcRequest,
    metadata?: grpcWeb.Metadata | null): Promise<calculator_pb.CalcResponse>;

  add(
    request: calculator_pb.CalcRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: calculator_pb.CalcResponse) => void): grpcWeb.ClientReadableStream<calculator_pb.CalcResponse>;

  add(
    request: calculator_pb.CalcRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: calculator_pb.CalcResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/calculator.Calculator/Add',
        request,
        metadata || {},
        this.methodDescriptorAdd,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/calculator.Calculator/Add',
    request,
    metadata || {},
    this.methodDescriptorAdd);
  }

  methodDescriptorMultiply = new grpcWeb.MethodDescriptor(
    '/calculator.Calculator/Multiply',
    grpcWeb.MethodType.UNARY,
    calculator_pb.CalcRequest,
    calculator_pb.CalcResponse,
    (request: calculator_pb.CalcRequest) => {
      return request.serializeBinary();
    },
    calculator_pb.CalcResponse.deserializeBinary
  );

  multiply(
    request: calculator_pb.CalcRequest,
    metadata?: grpcWeb.Metadata | null): Promise<calculator_pb.CalcResponse>;

  multiply(
    request: calculator_pb.CalcRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: calculator_pb.CalcResponse) => void): grpcWeb.ClientReadableStream<calculator_pb.CalcResponse>;

  multiply(
    request: calculator_pb.CalcRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: calculator_pb.CalcResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/calculator.Calculator/Multiply',
        request,
        metadata || {},
        this.methodDescriptorMultiply,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/calculator.Calculator/Multiply',
    request,
    metadata || {},
    this.methodDescriptorMultiply);
  }

}

